# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/grigorii_m/Projects/Pathfinding

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/grigorii_m/Projects/Pathfinding

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/grigorii_m/Projects/Pathfinding/CMakeFiles /home/grigorii_m/Projects/Pathfinding//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/grigorii_m/Projects/Pathfinding/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Pathfinding

# Build rule for target.
Pathfinding: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pathfinding
.PHONY : Pathfinding

# fast build rule for target.
Pathfinding/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathfinding.dir/build.make CMakeFiles/Pathfinding.dir/build
.PHONY : Pathfinding/fast

src/Grid.o: src/Grid.cpp.o
.PHONY : src/Grid.o

# target to build an object file
src/Grid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathfinding.dir/build.make CMakeFiles/Pathfinding.dir/src/Grid.cpp.o
.PHONY : src/Grid.cpp.o

src/Grid.i: src/Grid.cpp.i
.PHONY : src/Grid.i

# target to preprocess a source file
src/Grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathfinding.dir/build.make CMakeFiles/Pathfinding.dir/src/Grid.cpp.i
.PHONY : src/Grid.cpp.i

src/Grid.s: src/Grid.cpp.s
.PHONY : src/Grid.s

# target to generate assembly for a file
src/Grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathfinding.dir/build.make CMakeFiles/Pathfinding.dir/src/Grid.cpp.s
.PHONY : src/Grid.cpp.s

src/Pathfinder.o: src/Pathfinder.cpp.o
.PHONY : src/Pathfinder.o

# target to build an object file
src/Pathfinder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathfinding.dir/build.make CMakeFiles/Pathfinding.dir/src/Pathfinder.cpp.o
.PHONY : src/Pathfinder.cpp.o

src/Pathfinder.i: src/Pathfinder.cpp.i
.PHONY : src/Pathfinder.i

# target to preprocess a source file
src/Pathfinder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathfinding.dir/build.make CMakeFiles/Pathfinding.dir/src/Pathfinder.cpp.i
.PHONY : src/Pathfinder.cpp.i

src/Pathfinder.s: src/Pathfinder.cpp.s
.PHONY : src/Pathfinder.s

# target to generate assembly for a file
src/Pathfinder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathfinding.dir/build.make CMakeFiles/Pathfinding.dir/src/Pathfinder.cpp.s
.PHONY : src/Pathfinder.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathfinding.dir/build.make CMakeFiles/Pathfinding.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathfinding.dir/build.make CMakeFiles/Pathfinding.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathfinding.dir/build.make CMakeFiles/Pathfinding.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/tinyxml2.o: src/tinyxml2.cpp.o
.PHONY : src/tinyxml2.o

# target to build an object file
src/tinyxml2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathfinding.dir/build.make CMakeFiles/Pathfinding.dir/src/tinyxml2.cpp.o
.PHONY : src/tinyxml2.cpp.o

src/tinyxml2.i: src/tinyxml2.cpp.i
.PHONY : src/tinyxml2.i

# target to preprocess a source file
src/tinyxml2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathfinding.dir/build.make CMakeFiles/Pathfinding.dir/src/tinyxml2.cpp.i
.PHONY : src/tinyxml2.cpp.i

src/tinyxml2.s: src/tinyxml2.cpp.s
.PHONY : src/tinyxml2.s

# target to generate assembly for a file
src/tinyxml2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathfinding.dir/build.make CMakeFiles/Pathfinding.dir/src/tinyxml2.cpp.s
.PHONY : src/tinyxml2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Pathfinding"
	@echo "... src/Grid.o"
	@echo "... src/Grid.i"
	@echo "... src/Grid.s"
	@echo "... src/Pathfinder.o"
	@echo "... src/Pathfinder.i"
	@echo "... src/Pathfinder.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/tinyxml2.o"
	@echo "... src/tinyxml2.i"
	@echo "... src/tinyxml2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

